{
    "rules": {
        "users": {
            "$uid": {
                // Users can only read and write to their own profile node
                ".read": "auth != null && auth.uid == $uid",
                ".write": "auth != null && auth.uid == $uid",
                "activity": {
                    // Allow users to record their plays, skips, current song, etc.
                    ".write": "auth != null && auth.uid == $uid"
                },
                "taste": {
                    // Allow users (or backend on their behalf) to modify taste graph
                    ".write": "auth != null && auth.uid == $uid"
                },
                "recommendations": {
                    // Recommendations are generated by the backend worker. User has read only access.
                    ".read": "auth != null && auth.uid == $uid",
                    ".write": false
                }
            }
        }
    }
}